#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.wsl.demo.model
  mapperLocations: classpath:mapping/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080


---

#开发配置
spring:
  profiles: dev


  datasource:
    url: jdbc:mysql://localhost:3306/study_project?useOldAliasMetadataBehavior\=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: false
  #freemarker热部署配置
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
  resources:
    static-locations: classpath:/static/
  mail:
    host: smtp.exmail.qq.com
    username: 1209867203@qq.com
    password: aqyfybfyqxhojege
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
              required: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    password:
    #配置es
  data:
    elasticsearch:
      cluster-name: my-esLearn
      cluster-nodes: 172.16.60.50:9300
      repositories:
        enabled: true
#mq配置信息
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
      #开启TOPIC模式
  jms:
    pub-sub-domain: true





pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
